/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazCliente;

import Control.Tabla;
import PersistenciaException.PersistenciaException;
import datos.ClienteDAO;
import datos.ConexionBD;
import interfaces.IConexion;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import objetos.Cliente;
import objetos.Direccion;
import objetos.NombreCompleto;

/**
 *
 * @author rramirez
 */
public class dlgRegistro extends JDialog {
    
    private ClienteDAO clienteDAO;
    private JTable table;

    public dlgRegistro() {
        initComponents();
    }

    public void mostrar() {
        setLocationRelativeTo(null); // Centrar el diálogo en la pantalla
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        tituloTabla = new javax.swing.JLabel();
        ContraseñaLabel = new javax.swing.JLabel();
        CampoTextoContraseña = new javax.swing.JTextField();
        CampoTextoApMaterno = new javax.swing.JTextField();
        ApMaternoLabel = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        IdLabel2 = new javax.swing.JLabel();
        CampoTextoId1 = new javax.swing.JTextField();
        FechaNacimientoLabel = new javax.swing.JLabel();
        CampoTextoFechaNacimiento = new javax.swing.JTextField();
        ApPaternoLabel1 = new javax.swing.JLabel();
        CampoTextoApPaterno1 = new javax.swing.JTextField();
        CodigoPostalLabel = new javax.swing.JLabel();
        CampoTextoCodigoPostal = new javax.swing.JTextField();
        DatosPersonales1 = new javax.swing.JLabel();
        NombresLabel3 = new javax.swing.JLabel();
        CampoTextoNombres3 = new javax.swing.JTextField();
        CalleLabel = new javax.swing.JLabel();
        CampoTextoCalle = new javax.swing.JTextField();
        CiudadLabel1 = new javax.swing.JLabel();
        CampoTextoCiudad1 = new javax.swing.JTextField();
        NumeroExtLabel1 = new javax.swing.JLabel();
        CampoTextoNumeroExt1 = new javax.swing.JTextField();
        GuardarButton = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloTabla.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tituloTabla.setForeground(new java.awt.Color(0, 0, 0));
        tituloTabla.setText("Registro");
        jPanel1.add(tituloTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        ContraseñaLabel.setBackground(new java.awt.Color(0, 0, 0));
        ContraseñaLabel.setForeground(new java.awt.Color(0, 0, 0));
        ContraseñaLabel.setText("Contraseña:");
        jPanel1.add(ContraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        CampoTextoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        CampoTextoContraseña.setForeground(new java.awt.Color(0, 0, 0));
        CampoTextoContraseña.setCaretColor(new java.awt.Color(255, 102, 102));
        CampoTextoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(CampoTextoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 160, 20));

        CampoTextoApMaterno.setBackground(new java.awt.Color(255, 255, 255));
        CampoTextoApMaterno.setForeground(new java.awt.Color(0, 0, 0));
        CampoTextoApMaterno.setCaretColor(new java.awt.Color(255, 102, 102));
        CampoTextoApMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoApMaternoActionPerformed(evt);
            }
        });
        jPanel1.add(CampoTextoApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 160, 20));

        ApMaternoLabel.setBackground(new java.awt.Color(0, 0, 0));
        ApMaternoLabel.setForeground(new java.awt.Color(0, 0, 0));
        ApMaternoLabel.setText("Apellido materno:");
        jPanel1.add(ApMaternoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        Direccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Direccion.setForeground(new java.awt.Color(0, 0, 0));
        Direccion.setText("Dirección");
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        IdLabel2.setBackground(new java.awt.Color(0, 0, 0));
        IdLabel2.setForeground(new java.awt.Color(0, 0, 0));
        IdLabel2.setText("ID:");
        jPanel1.add(IdLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        CampoTextoId1.setBackground(new java.awt.Color(255, 255, 255));
        CampoTextoId1.setForeground(new java.awt.Color(0, 0, 0));
        CampoTextoId1.setCaretColor(new java.awt.Color(255, 102, 102));
        CampoTextoId1.setSelectionColor(new java.awt.Color(255, 102, 102));
        CampoTextoId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoId1ActionPerformed(evt);
            }
        });
        jPanel1.add(CampoTextoId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 160, 20));

        FechaNacimientoLabel.setBackground(new java.awt.Color(0, 0, 0));
        FechaNacimientoLabel.setForeground(new java.awt.Color(0, 0, 0));
        FechaNacimientoLabel.setText("Fecha de nacimiento:");
        jPanel1.add(FechaNacimientoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        CampoTextoFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        CampoTextoFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        CampoTextoFechaNacimiento.setCaretColor(new java.awt.Color(255, 102, 102));
        CampoTextoFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoFechaNacimientoActionPerformed(evt);
            }
        });
        jPanel1.add(CampoTextoFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 160, 20));

        ApPaternoLabel1.setBackground(new java.awt.Color(0, 0, 0));
        ApPaternoLabel1.setForeground(new java.awt.Color(0, 0, 0));
        ApPaternoLabel1.setText("Apellido paterno:");
        jPanel1.add(ApPaternoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        CampoTextoApPaterno1.setBackground(new java.awt.Color(255, 255, 255));
        CampoTextoApPaterno1.setForeground(new java.awt.Color(0, 0, 0));
        CampoTextoApPaterno1.setCaretColor(new java.awt.Color(255, 102, 102));
        CampoTextoApPaterno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoApPaterno1ActionPerformed(evt);
            }
        });
        jPanel1.add(CampoTextoApPaterno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 160, 20));

        CodigoPostalLabel.setBackground(new java.awt.Color(0, 0, 0));
        CodigoPostalLabel.setForeground(new java.awt.Color(0, 0, 0));
        CodigoPostalLabel.setText("Numero Exterior:");
        jPanel1.add(CodigoPostalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        CampoTextoCodigoPostal.setBackground(new java.awt.Color(255, 255, 255));
        CampoTextoCodigoPostal.setForeground(new java.awt.Color(0, 0, 0));
        CampoTextoCodigoPostal.setCaretColor(new java.awt.Color(255, 102, 102));
        CampoTextoCodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoCodigoPostalActionPerformed(evt);
            }
        });
        jPanel1.add(CampoTextoCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 120, 20));

        DatosPersonales1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DatosPersonales1.setForeground(new java.awt.Color(0, 0, 0));
        DatosPersonales1.setText("Datos personales");
        jPanel1.add(DatosPersonales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        NombresLabel3.setBackground(new java.awt.Color(0, 0, 0));
        NombresLabel3.setForeground(new java.awt.Color(0, 0, 0));
        NombresLabel3.setText("Nombre(s):");
        jPanel1.add(NombresLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        CampoTextoNombres3.setBackground(new java.awt.Color(255, 255, 255));
        CampoTextoNombres3.setForeground(new java.awt.Color(0, 0, 0));
        CampoTextoNombres3.setCaretColor(new java.awt.Color(255, 102, 102));
        CampoTextoNombres3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoNombresActionPerformed(evt);
            }
        });
        jPanel1.add(CampoTextoNombres3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 160, 20));

        CalleLabel.setBackground(new java.awt.Color(0, 0, 0));
        CalleLabel.setForeground(new java.awt.Color(0, 0, 0));
        CalleLabel.setText("Ciudad:");
        jPanel1.add(CalleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        CampoTextoCalle.setBackground(new java.awt.Color(255, 255, 255));
        CampoTextoCalle.setForeground(new java.awt.Color(0, 0, 0));
        CampoTextoCalle.setCaretColor(new java.awt.Color(255, 102, 102));
        CampoTextoCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoCalleActionPerformed(evt);
            }
        });
        jPanel1.add(CampoTextoCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, 20));

        CiudadLabel1.setBackground(new java.awt.Color(0, 0, 0));
        CiudadLabel1.setForeground(new java.awt.Color(0, 0, 0));
        CiudadLabel1.setText("Calle:");
        jPanel1.add(CiudadLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        CampoTextoCiudad1.setBackground(new java.awt.Color(255, 255, 255));
        CampoTextoCiudad1.setForeground(new java.awt.Color(0, 0, 0));
        CampoTextoCiudad1.setCaretColor(new java.awt.Color(255, 102, 102));
        CampoTextoCiudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoCiudad1ActionPerformed(evt);
            }
        });
        jPanel1.add(CampoTextoCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 120, 20));

        NumeroExtLabel1.setBackground(new java.awt.Color(0, 0, 0));
        NumeroExtLabel1.setForeground(new java.awt.Color(0, 0, 0));
        NumeroExtLabel1.setText("Numero Exterior:");
        jPanel1.add(NumeroExtLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        CampoTextoNumeroExt1.setBackground(new java.awt.Color(255, 255, 255));
        CampoTextoNumeroExt1.setForeground(new java.awt.Color(0, 0, 0));
        CampoTextoNumeroExt1.setCaretColor(new java.awt.Color(255, 102, 102));
        CampoTextoNumeroExt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoNumeroExt1ActionPerformed(evt);
            }
        });
        jPanel1.add(CampoTextoNumeroExt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 120, 20));

        GuardarButton.setText("Guardar");
        GuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GuardarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 80, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inter.png"))); // NOI18N
        Fondo.setText("jLabel1");
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CampoTextoApMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoApMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextoApMaternoActionPerformed

    private void CampoTextoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextoContraseñaActionPerformed

    private void CampoTextoFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextoFechaNacimientoActionPerformed

    private void CampoTextoApPaterno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoApPaterno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextoApPaterno1ActionPerformed

    private void CampoTextoCodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoCodigoPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextoCodigoPostalActionPerformed

    private void CampoTextoNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextoNombresActionPerformed

    private void CampoTextoCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextoCalleActionPerformed

    private void CampoTextoCiudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoCiudad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextoCiudad1ActionPerformed

    private void CampoTextoNumeroExt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoNumeroExt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextoNumeroExt1ActionPerformed

    private void CampoTextoId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextoId1ActionPerformed

    private void GuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarButtonActionPerformed
        // Obtener los datos ingresados en los campos de texto
        String nombre = CampoTextoNombres3.getText();
        String apPaterno = CampoTextoApPaterno1.getText();
        String apMaterno = CampoTextoApMaterno.getText();
        String fechaNacimiento = CampoTextoFechaNacimiento.getText();
        String calle = CampoTextoCalle.getText();
        String ciudad = CampoTextoCiudad1.getText();
        String numExterior = CampoTextoNumeroExt1.getText();
        String cp = CampoTextoCodigoPostal.getText();

        // Crear un objeto de la clase NombreCompleto con los datos ingresados
        NombreCompleto nombreCompleto = new NombreCompleto();
        nombreCompleto.setNombres(nombre);
        nombreCompleto.setApPaterno(apPaterno);
        nombreCompleto.setApMaterno(apMaterno);

        // Crear un objeto de la clase Direccion con los datos ingresados
        Direccion direccion = new Direccion();
        direccion.setCalle(calle);
        direccion.setColonia(ciudad);
        direccion.setNumExterior(numExterior);
        direccion.setCp(cp);

        // Crear un objeto de la clase Cliente con los datos ingresados
        Cliente cliente = new Cliente();
        cliente.setNombreCompleto(nombreCompleto);
        // También podrías asignar la fecha de nacimiento si es relevante para tu aplicación
        // cliente.setFechaNacimiento(fechaNacimiento);
        cliente.setDireccion(direccion);

        try {
            // Llamar al método registrarCliente del clienteDAO para guardar el cliente en la base de datos
            clienteDAO.registrarCliente(cliente);
            // Aquí podrías mostrar un mensaje de éxito al usuario
        } catch (PersistenciaException ex) {
            // Manejo de la excepción en caso de error al guardar el cliente en la base de datos
            ex.printStackTrace(); // Otra opción sería mostrar un mensaje de error al usuario
        }
    }//GEN-LAST:event_GuardarButtonActionPerformed

    private void centraVentana() {
        //Obtiene el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Obtiene el tamaño de la ventana de la aplicación
        Dimension frameSize = getSize();

        // Se asegura que el tamaño de la ventana de la aplicación
        // no exceda el tamaño de la pantalla
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }

        // Centra la ventana de la aplicación sobre la pantalla
        setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    public void despliegaTabla(Tabla tabla) {
        // Create the table from the table model with the column titles and cell values
        jtabla = new javax.swing.JTable(tabla.getModeloTabla());
        // Set the table title
        tituloTabla.setText(tabla.getTitulo());
        // Set the layout of the JScrollPane containing the table
        jPanel1.setLayout(new java.awt.BorderLayout());
        // Add the JScrollPane with the table to the panel
        jPanel1.add(new JScrollPane(jtabla), java.awt.BorderLayout.CENTER);
    }

     public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            dlgRegistro dialog = new dlgRegistro();
            dialog.mostrar();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApMaternoLabel;
    private javax.swing.JLabel ApPaternoLabel1;
    private javax.swing.JLabel CalleLabel;
    private javax.swing.JTextField CampoTextoApMaterno;
    private javax.swing.JTextField CampoTextoApPaterno1;
    private javax.swing.JTextField CampoTextoCalle;
    private javax.swing.JTextField CampoTextoCiudad1;
    private javax.swing.JTextField CampoTextoCodigoPostal;
    private javax.swing.JTextField CampoTextoContraseña;
    private javax.swing.JTextField CampoTextoFechaNacimiento;
    private javax.swing.JTextField CampoTextoId1;
    private javax.swing.JTextField CampoTextoNombres3;
    private javax.swing.JTextField CampoTextoNumeroExt1;
    private javax.swing.JLabel CiudadLabel1;
    private javax.swing.JLabel CodigoPostalLabel;
    private javax.swing.JLabel ContraseñaLabel;
    private javax.swing.JLabel DatosPersonales1;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel FechaNacimientoLabel;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton GuardarButton;
    private javax.swing.JLabel IdLabel2;
    private javax.swing.JLabel NombresLabel3;
    private javax.swing.JLabel NumeroExtLabel1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloTabla;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JTable jtabla;

}
